replicaCount: 1

image:
  repository: harbor-platform.apps.ocp01.npd.co/aiops/remediation-controller
  tag: "0.5.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-pull-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: remediation-controller

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

route:
  enabled: false
  host: ""
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  logLevel: INFO
  policyConfigMap: aiops-remediation-policy
  policyConfigMapKey: policy.yaml
  gitopsTargetsConfigMap: aiops-gitops-targets
  gitopsTargetsKey: targets.yaml
  platformEnvironment: "dev-ocp"

otel:
  enabled: true
  endpoint: "http://opentelemetry-collector.observability.svc.cluster.local:4317"
  protocol: "grpc"
  serviceName: "remediation-controller"
  resourceAttributes: "deployment.environment=dev-ocp,k8s.namespace.name=aiops-automation,k8s.cluster.name=ocp01"

database:
  existingSecret: ""
  urlKey: DATABASE_URL

github:
  existingSecret: ""
  tokenKey: pat
  usernameKey: username

ansible:
  jobImage: "bitnami/kubectl:1.30"

amcSync:
  enabled: true
  schedule: "*/15 * * * *"
  serviceAccountName: aiops-amc-sync
  webhookUrl: http://incident-api.aiops-core.svc.cluster.local:8080/api/v1/alerts
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3

probes:
  liveness:
    path: /health/live
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health/ready
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

volumes:
  tmp:
    enabled: true
    sizeLimit: 32Mi

nodeSelector: {}
tolerations: []
affinity: {}
