apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - harbor-pull-external-secret.yaml
  - harbor-pull-automation-external-secret.yaml
  - aiops-db-external-secret.yaml
  - app-external-secret.yaml
  - app-automation-external-secret.yaml
  - github-automation-external-secret.yaml
  - openai-external-secret.yaml
  - grafana-external-secrets.yaml
