replicaCount: 1

image:
  repository: harbor-platform.apps.ocp01.npd.co/aiops/aiops-console
  tag: "0.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-pull-secret

fullnameOverride: aiops-console

serviceAccount:
  create: true
  name: aiops-console

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
