# RCA Agent — Phase 3 (Harbor image via Jenkins Kaniko)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rca-agent
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: open-aiops-platform
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: aiops-platform
  source:
    repoURL: https://github.com/kevinram164/Open-Source-AIOps-Platform.git
    targetRevision: main
    path: charts/rca-agent
    helm:
      valueFiles:
        - ../../gitops/environments/dev-ocp/values-rca-agent.yaml
        - ../../gitops/values-images-rca-agent.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aiops-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
